cabal-version:      3.8
name:               recipe-viz
version:            0.1.0.0
synopsis:           Haskell project that calls the OpenAI API
description:        Calls the OpenAI API (e.g. for a joke) using API key from environment.
license:            MIT
author:             Author name here
maintainer:         example@example.com

executable recipe-viz
  main-is:          Main.hs
  build-depends:
    base >=4.17 && <5,
    openai >=2.2,
    dotenv >=0.12,
    text,
    vector,
    http-client,
    http-client-tls,
    bytestring
  default-language: Haskell2010
  ghc-options:      -Wall
